timezone: 'Australia/Perth'
monday:
  from: '09:00'
  to: '17:00'
tuesday:
  from: '09:00'
  to: '17:00'
wednesday:
  from: '09:00'
  to: '17:00'
thursday:
  from: '09:00'
  to: '17:00'
friday:
  from: '09:00'
  to: '17:00'
saturday:
  from: '09:00'
  to: '17:00'
sunday:
  from: '09:00'
  to: '17:00'
